layout_spectrum: 0.8667597
typography_spectrum: 0.9492559
color:
  lightness: 0.603878
  brandStrength: 0.4824507
  saturation: 0.9074835
  rhythmicContrast: 0.750461
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
name: Joyce Renee Quilting
